# 不要问了，全用yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proj
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proj
  template:
    metadata:
      name: proj
      labels:
        app: proj
    spec:
      containers:
        - image: proj:myapp
          name: proj-web
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: proj-svc
  namespace: demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8081
      nodePort: 30123
  selector:
    app: proj
