spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/redis?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
     #host.docker.internal, localhost
    url: aws sql usrl
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    database: mysql 
    generate-ddl: true 
    show-sql: true 
    database-platform: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: redis.8zab09.clustercfg.use2.cache.amazonaws.com
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  mail:
    host: smtp.gmail.com
    username: your email address
    password: email password #Gmail user-pass
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 465
    properties.mail.display.sendmail: Javen
    properties.mail.display.sendname: Spring Boot Guide Email
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    from: same as the username
    default-encoding: utf-8
#https port.
server:
  port: 8081
  # https port=443
  #ssl:
  #    key-store: classpath:keystore.p12
  #    key-store-password: guoguo841268
  #    key-store-type: PKCS12
  #    key-alias: tomcat#

